version: '3.8'

services:
  postgres:
    image: postgres:12.18-bullseye
    container_name: postgres_container
    volumes:
      - go-psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: admindb
    networks:
        - postgres

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"
    networks:
        - postgres

networks:
  postgres:
    driver: bridge

volumes:
  go-psql:
    external: true

